Patrowl/PatrowlEngines

.travis.yml, tests/test_sample.py
Adds support for Travis
Adds a basic unit test
=> Add Travis support

engines/owl_code/Dockerfile, engines/owl_leaks/Dockerfile
related to:"OWL_CODE and OWL_LEAKS use PatrowlEnginesUtil"
=> Remove copying of the utils-directory as it is missing

engines/skeleton/README.md, engines/skeleton/__init__.py, engines/skeleton/engine-skeleton.py, engines/skeleton/requirements.txt, engines/skeleton/skeleton.json, engines/skeleton/skeleton.json.sample
This is an example of a nutshell engine named : skeleton
It should be easier to start an engine from scratch.
=> [skeleton] Add initial code

engines/openvas/README.md, engines/openvas/__init__.py, engines/openvas/engine-openvas.py, engines/openvas/openvas.json.sample, engines/openvas/requirements.txt
The engine is able to generate a report from a task_id and then attach issues to the related assets (based on IP, FQDN are resolved).
This match only my use case for now, but it's a good start.
=> [openvas] Initial commit

.travis.yml, engines/nessus/tests/test_nessus.py, engines/nmap/tests/test_nmap.py, engines/ssllabs/Dockerfile, engines/ssllabs/__init__.py, engines/ssllabs/engine-ssllabs.py, engines/virustotal/Dockerfile, engines/virustotal/__init__.py, engines/virustotal/engine-virustotal.py
- Remove copy of utils in engine directory (since PatrowlEnginesUtils>=0.0.12)
- Force requests>=2.22.0 (avoid incompatibility with urllib)
- Remove PatrowlEnginesUtils import from local utils
- Remove PatrowlEnginesUtils import from local utils
- Lint
- Check if "details" is present in results (avoid crash)
- Check if "scan_ip" is present in asset findings (avoid crash)
=> [nmap][nessus][ssllabs][virustotal] Fix tests and code

.gitignore, engines/certstream/README.md, engines/certstream/__init__.py, engines/certstream/certstream.json.sample, engines/certstream/engine-certstream.py, engines/certstream/requirements.txt, engines/certstream/whitelist.txt.sample, engines/eyewitness/README.md, engines/eyewitness/__init__.py, engines/eyewitness/engine-eyewitness.py, engines/eyewitness/eyewitness.json.sample, engines/eyewitness/requirements.txt, engines/nmap/engine-nmap.py, engines/nmap/tests/test_nmap.py, engines/ssllabs/engine-ssllabs.py, engines/utils/PatrowlEngineTest.py
- Add engine
- Add engine
- Make PID error logged but I don't understand why it's happening sometimes
- Comment "test_nmap_vulners" test which sometimes fails (not only on Travis, i can reproduce it)
- Fix encoding issue
- Fix when checking the result is in failure
- Log returned error
=> CertStream, EyeWitness and fixes

engines/openvas/engine-openvas-omp.py
Big update of Openvas version "OMP"
**Features**:
- Feature : In failure assets are now reported
- Feature : Sort issues in the findings by severity
**Fixtures**:
- Fix : link is now clickable
- Fix: json.loads payload["options"]
- Fix: Bad '%' before SSH Port
- Fix : Remove OpenVAS connection. For GVM ?
- Fix : Logic failure in scan
**Other** : 
- Factorize get_criticity function
- Allow "true", not just "True" in options
- Remove gvm-cli comments, maybe in engine-openvas-gvm.py
- Keep the verbose print... Still in debug mode... It could be improved
=> [openvas] Sort result and other fixes

engines/nmap/engine-nmap.py
Fixed AttributeError: 'str' object has no attribute 'keys'
=> Fix AttributeError

engines/certstream/Dockerfile, engines/certstream/engine-certstream.py
**Fixture**:
- Fix options payload to support a str instead of a dict
**Feature**:
- Upgrade pip during docker build
=> [certstream] Fixtures to support Manager in py3

engines/arachni/Dockerfile, engines/certstream/Dockerfile, engines/cortex/Dockerfile, engines/eyewitness/Dockerfile, engines/nessus/Dockerfile, engines/nmap/Dockerfile, engines/openvas/Dockerfile, engines/owl_dns/Dockerfile, engines/owl_leaks/Dockerfile, engines/sslscan/Dockerfile, engines/urlvoid/Dockerfile, engines/virustotal/Dockerfile, scripts/start-docker-engines.sh
Currently we don't have any log from docker, it's really painfull for debugging.
=> docker : displays logs to stdout

engines/certstream/engine-certstream.py, engines/eyewitness/README.md, engines/eyewitness/engine-eyewitness.py, engines/eyewitness/eyewitness.json.sample
**Features**:
- Compare taken http and https screenshot
- Finding if difference between previous screenshot with new one is above a threshold
**Features**:
- Logs with logging
- Reduce criticity of a pingeable asset 10 -> 7
- Add ceil and cvss in global variable
=> [eyewitness][certstream] upgrade

engines/virustotal/engine-virustotal.py
**Fixtures**
- Make sure that "positives" exists in results, sometimes crashes
=> [virustotal] fix no positive issue

.gitignore, engines/certstream/engine-certstream.py
**Fixtures**:
- Fix subdomains in whitelist
- Add default value if no options set
**Feature**:
- Possibility to set custom settings in arg
=> [certstream] Add stability fix

engines/eyewitness/engine-eyewitness.py
=> [eyewitness] Add retry

.gitignore, engines/eyewitness/engine-eyewitness.py, engines/eyewitness/eyewitness.json.sample
**Features**:
- Add is_forsale function which returns True is one rule match the report sources
=> Eyewitness upgrade: parametrize CEIL & add is_forsale function

.gitignore, .travis.yml, engines/wpscan/Dockerfile, engines/wpscan/README.md, engines/wpscan/__init__.py, engines/wpscan/engine-wpscan.py, engines/wpscan/requirements.txt, engines/wpscan/tests/test_wpscan.py, engines/wpscan/wpscan.json.sample
**Feature**:
- Add WPSCAN engine, able to scan wordpress with or without api-token (from https://wpvulndb.com/). It's easy to add parameters in the WPSCAN policy with the "extra_args" option.
=> Add wpscan engine

engines/apivoid/Dockerfile, engines/apivoid/README.md, engines/apivoid/__init__.py, engines/apivoid/apivoid.json.sample, engines/apivoid/tests/test_apivoid.py, engines/eyewitness/Dockerfile, engines/eyewitness/__init__.py, engines/eyewitness/eyewitness.json.sample
=> Fix apivoid

engines/nessus/engine-nessus.py, engines/nessus/requirements.txt
=> Save status data to TinyDB  Tha way data will persist after process restart

engines/nessus/engine-nessus.py, engines/nessus/requirements.txt
Nessus Engine Fixes to avoid Tinydb corruption (Tinydb does not support multiprocess)
=> Nessus Engine Fixes to avoid Tinydb corruption (Tinydb does not support multiprocess)

engines/cybelangel/README.md, engines/cybelangel/__init__.py, engines/cybelangel/cybelangel.json.sample, engines/cybelangel/cybelangel.py, engines/cybelangel/engine-cybelangel.py, engines/cybelangel/requirements.txt
Hey, I wrote an engine for cybelangel.
The purpose of this engine is to get malicious websites reported by [CybelAngel](https://cybelangel.com/), add them in Patrowl and move them to the *resolved* state in CybelAngel.
It uses the CybelAngel's API.
This is my first engine, I may have forget something, don't hesitate to contact me for any information!
Signed-off-by: Fabien Martinez <fabien.martinez@adevinta.com>
=> [cybelangel]: Add cybelangel engine

engines/shhgit/engine-shhgit.py, engines/shhgit/libs/git_leaks.py, engines/shhgit/libs/github.py, engines/shhgit/shhgit.json.sample
There were some basic issues like:
- no `assets` in engine
- logger issue for gunicorn
- [gitignore]: Create .gitignore
- [shhgit]: Create new engine
- [requirements.txt]: Update requirements for python
- [shhgit]: Update version
- [shhgit]: Add logger to use gunicorn easily
- [shhgit]: Fix assets issue and typo
- [shhgit]: Use logger from argument
=> [Engine Shhgit] Fix some issues

engines/owl_dns/engine-owl_dns.py, engines/owl_dns/modules/dkimsignatures.py, engines/owl_dns/owl_dns.json.sample, engines/owl_dns/tests/test_owl_dns.py
Testing SPF inside owl_dns before merge
=> Feature spf

engines/shhgit/engine-shhgit.py, engines/shhgit/libs/git_leaks.py, engines/shhgit/libs/github.py
Signed-off-by: Fabien Martinez <fabien.martinez@adevinta.com>
=> [engine shhgit]: Fix duplicate and logger

engines/nmap/engine-nmap.py
- Fix #270 
- Multiple CPE on service is functionnal:
=> Multiple CPE on service with CPE #270

engines/nmap/banner.py, engines/owl_dns/engine-owl_dns.py
=> Fix #279 owl_dns: support 'email' as asset datatype

engines/owl_dns/engine-owl_dns.py
try to fix findings gestion for SPF in owl dns engine
CHECK #277, this pr is now useless
=> create finding for each spf dns entry
